In [1]:
import numpy as np
import pandas as pd

import sklearn

YEARS = set()

table = dict()
table["population"]  = pd.read_csv("data/population.csv")
table["pcgdp"]       = pd.read_csv("data/pcgdp.csv")
table["electricity"] = pd.read_csv("data/electricity.csv")
winter_raw = pd.read_csv("data/winter.csv")



DROP_FROM = 1960
DROP_TO = 1991
years_to_drop = [str(i) for i in range(DROP_FROM, DROP_TO)]
for key, _ in table.items():
    print(key)
    table[key] = table[key].drop(columns=years_to_drop+["Country Name", "Indicator Name", "Indicator Code"])
    table[key] = table[key].rename(index=str, columns={"Country Code":"Country"})


population
pcgdp
electricity


In [2]:
table["population"].head(3)

Country        1991        1992        1993        1994        1995  \
0     ABW     64622.0     68235.0     72504.0     76700.0     80324.0   
1     AFG  12993657.0  13981231.0  15095099.0  16172719.0  17099541.0   
2     AGO  12553446.0  12968345.0  13403734.0  13841301.0  14268994.0   

         1996        1997        1998        1999     ...             2009  \
0     83200.0     85451.0     87277.0     89005.0     ...         101453.0   
1  17822884.0  18381605.0  18863999.0  19403676.0     ...       28004331.0   
2  14682284.0  15088981.0  15504318.0  15949766.0     ...       22549547.0   

         2010        2011        2012        2013        2014        2015  \
0    101669.0    102053.0    102577.0    103187.0    103795.0    104341.0   
1  28803167.0  29708599.0  30696958.0  31731688.0  32758020.0  33736494.0   
2  23369131.0  24218565.0  25096150.0  25998340.0  26920466.0  27859305.0   

         2016  2017  Unnamed: 62  
0    104822.0   NaN          NaN  
1  34656032.0   NaN          NaN  
2  28813463.0   NaN          NaN  

[3 rows x 29 columns]

In [3]:
table["population"].describe()

1991          1992          1993          1994          1995  \
count  2.620000e+02  2.610000e+02  2.610000e+02  2.610000e+02  2.620000e+02   
mean   2.134405e+08  2.178132e+08  2.213804e+08  2.249049e+08  2.275715e+08   
std    6.836446e+08  6.961000e+08  7.073090e+08  7.183989e+08  7.282225e+08   
min    9.053000e+03  9.109000e+03  9.156000e+03  9.190000e+03  9.230000e+03   
25%    1.045433e+06  1.062800e+06  1.088569e+06  1.112846e+06  1.126123e+06   
50%    7.147575e+06  7.382000e+06  7.495000e+06  7.583954e+06  7.655178e+06   
75%    4.276932e+07  4.374796e+07  4.419463e+07  4.464154e+07  4.462919e+07   
max    5.375489e+09  5.459754e+09  5.544873e+09  5.628791e+09  5.713794e+09   

               1996          1997          1998          1999          2000  \
count  2.620000e+02  2.620000e+02  2.630000e+02  2.630000e+02  2.630000e+02   
mean   2.310352e+08  2.345038e+08  2.370261e+08  2.404018e+08  2.437446e+08   
std    7.391476e+08  7.500845e+08  7.595665e+08  7.701604e+08  7.805903e+08   
min    9.256000e+03  9.277000e+03  9.306000e+03  9.345000e+03  9.420000e+03   
25%    1.140262e+06  1.156145e+06  1.166084e+06  1.198096e+06  1.231483e+06   
50%    7.740222e+06  7.854552e+06  7.913000e+06  7.992324e+06  8.048600e+06   
75%    4.509184e+07  4.555807e+07  4.562322e+07  4.625767e+07  4.704225e+07   
max    5.796632e+09  5.879434e+09  5.961166e+09  6.041819e+09  6.121683e+09   

          ...               2009          2010          2011          2012  \
count     ...       2.630000e+02  2.630000e+02  2.630000e+02  2.620000e+02   
mean      ...       2.743725e+08  2.779127e+08  2.814389e+08  2.861268e+08   
std       ...       8.736656e+08  8.842899e+08  8.949399e+08  9.073509e+08   
min       ...       1.002800e+04  1.002500e+04  1.005700e+04  1.027900e+04   
25%       ...       1.425982e+06  1.443678e+06  1.465471e+06  1.415726e+06   
50%       ...       9.298515e+06  9.378126e+06  9.460802e+06  9.624267e+06   
75%       ...       5.038575e+07  5.087028e+07  5.140827e+07  5.249529e+07   
max       ...       6.849573e+09  6.932881e+09  7.014999e+09  7.099549e+09   

               2013          2014          2015          2016  2017  \
count  2.620000e+02  2.620000e+02  2.620000e+02  2.620000e+02   0.0   
mean   2.898075e+08  2.935173e+08  2.972352e+08  3.009801e+08   NaN   
std    9.183373e+08  9.293896e+08  9.404528e+08  9.515836e+08   NaN   
min    1.081900e+04  1.090800e+04  1.100100e+04  1.109700e+04   NaN   
25%    1.431560e+06  1.447306e+06  1.471523e+06  1.522803e+06   NaN   
50%    9.746730e+06  9.879129e+06  1.002115e+07  1.012427e+07   NaN   
75%    5.318760e+07  5.396340e+07  5.493841e+07  5.590466e+07   NaN   
max    7.185078e+09  7.271228e+09  7.357370e+09  7.444027e+09   NaN   

       Unnamed: 62  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 28 columns]

In [4]:
table["pcgdp"].head(3)

Country        1991       1992        1993          1994          1995  \
0     ABW         NaN        NaN         NaN  17342.471940  16441.790636   
1     AFG         NaN        NaN         NaN           NaN           NaN   
2     AGO  965.361296  438.32052  393.784521    293.278222    353.182045   

           1996          1997          1998          1999     ...       \
0  16585.195531  17926.572836  19081.351656  19356.203389     ...        
1           NaN           NaN           NaN           NaN     ...        
2    512.620966    506.884952    415.693346    385.768853     ...        

           2009          2010          2011         2012         2013  \
0  24631.434860  24271.940421  25324.720362          NaN          NaN   
1    445.893298    553.300289    603.537023   669.009051   638.612543   
2   3347.844850   3529.053482   4299.012889  4598.249988  4804.616884   

          2014         2015         2016  2017  Unnamed: 62  
0          NaN          NaN          NaN   NaN          NaN  
1   629.345250   569.577923   561.778746   NaN          NaN  
2  4709.312024  3695.793748  3308.700233   NaN          NaN  

[3 rows x 29 columns]

In [5]:
table["pcgdp"].describe()

1991          1992          1993          1994           1995  \
count    222.000000    222.000000    226.000000    228.000000     237.000000   
mean    6001.202196   6313.158199   6057.158066   6364.049259    7132.467571   
std    10110.437511  10858.826337  10352.997481  11032.680085   12487.731776   
min      137.982562    110.494288     80.190056     65.676877      65.011416   
25%      584.260446    502.122344    531.292854    510.524476     576.052319   
50%     1585.728777   1552.272887   1529.089541   1637.068757    1991.514981   
75%     5920.502507   6668.179237   6342.492165   6147.517252    6748.931109   
max    83732.701453  91654.119007  85421.725834  89404.073321  101993.122374   

                1996          1997          1998          1999          2000  \
count     238.000000    237.000000    239.000000    240.000000    245.000000   
mean     7456.511874   7214.650849   7426.157078   7757.638559   7629.505394   
std     12714.418882  11872.491426  12279.230340  12826.784611  12334.475766   
min        72.746225    125.462747    124.505623    102.644799    123.876206   
25%       585.832861    586.284330    576.151893    591.547675    622.742748   
50%      2111.864948   2056.200186   2006.256910   1930.576538   1854.145956   
75%      7219.309007   7327.934445   7900.620838   8151.498599   8601.185906   
max    101328.794623  90882.921883  93093.258537  91383.940493  82534.873767   

          ...                2009           2010           2011  \
count     ...          250.000000     250.000000     250.000000   
mean      ...        13588.866203   14298.180545   15736.871568   
std       ...        21079.805989   21638.192903   23893.064298   
min       ...          204.944650     231.194326     260.479907   
25%       ...         1255.853139    1555.547218    1703.504313   
50%       ...         4622.612335    5133.442629    5765.315089   
75%       ...        14671.958610   15639.528114   17243.737156   
max       ...       152111.598027  144246.368775  162009.877819   

                2012           2013           2014           2015  \
count     246.000000     247.000000     246.000000     245.000000   
mean    15104.972230   15573.331378   15515.773872   13917.350066   
std     21606.460500   22787.792617   22812.716950   20393.585544   
min       265.285605     282.755525     312.748979     300.676557   
25%      1770.871134    1861.059425    2010.251039    1862.167274   
50%      6338.000552    6353.826383    6382.782373    5814.863134   
75%     16260.804677   16604.059578   16474.291830   16129.049283   
max    149295.646044  173528.150454  179308.075616  168146.015281   

                2016  2017  Unnamed: 62  
count     237.000000   0.0          0.0  
mean    12745.478087   NaN          NaN  
std     17172.690157   NaN          NaN  
min       285.727442   NaN          NaN  
25%      1772.215255   NaN          NaN  
50%      5274.546008   NaN          NaN  
75%     14912.686543   NaN          NaN  
max    100738.684223   NaN          NaN  

[8 rows x 28 columns]

In [6]:
table["electricity"].head(3)

Country       1991       1992       1993       1994       1995       1996  \
0     ABW  88.780846  89.115829  89.447754  89.773560  90.090187  90.394585   
1     AFG   0.010000   0.010000   0.010000   0.010000   0.010000   0.010000   
2     AGO  12.579379  13.760440  14.938441  16.110325  17.273031  18.423502   

        1997       1998       1999     ...            2009       2010  \
0  90.683678  90.954422  91.203751     ...       93.354546  93.356292   
1   0.010000   0.021977   0.179635     ...       44.854885  42.700000   
2  19.558676  20.675495  21.770901     ...       32.382469  33.514950   

        2011       2012       2013       2014       2015       2016  2017  \
0  93.942375  94.255814  94.578262  94.906723  95.238182  95.570145   NaN   
1  43.222019  69.100000  67.259552  89.500000  71.500000  84.137138   NaN   
2  34.600000  35.821964  36.990490  32.000000  42.000000  40.520607   NaN   

   Unnamed: 62  
0          NaN  
1          NaN  
2          NaN  

[3 rows x 29 columns]

In [7]:
table["electricity"].describe()

1991        1992        1993        1994        1995        1996  \
count  251.000000  251.000000  251.000000  252.000000  255.000000  256.000000   
mean    66.970359   67.658785   68.201201   68.819778   69.769111   70.652038   
std     37.142282   36.800202   36.501999   36.156386   35.648829   35.136836   
min      0.010000    0.010000    0.010000    0.010000    0.010000    0.010000   
25%     33.616261   35.203474   36.787632   36.670809   41.066517   42.748812   
50%     86.442174   86.580068   87.418197   87.841311   88.487887   89.426833   
75%    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
max    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   

             1997        1998        1999        2000     ...       \
count  256.000000  256.000000  256.000000  257.000000     ...        
mean    71.184804   71.885474   72.603323   73.240085     ...        
std     34.805971   34.261124   33.782445   33.369147     ...        
min      0.010000    0.010000    0.010000    0.010000     ...        
25%     42.380551   44.879803   47.375000   49.958664     ...        
50%     89.824309   90.496158   91.062653   91.579251     ...        
75%    100.000000  100.000000  100.000000  100.000000     ...        
max    100.000000  100.000000  100.000000  100.000000     ...        

             2009        2010        2011        2012        2013        2014  \
count  261.000000  261.000000  261.000000  261.000000  261.000000  261.000000   
mean    78.813311   78.801051   79.899944   80.799870   81.297611   82.082864   
std     29.788237   29.923153   28.842930   28.300432   28.055591   27.352842   
min      1.900000    0.000000    3.918669    4.912345    5.915033    6.923728   
25%     62.982807   64.350000   66.062515   68.796662   69.796356   71.673798   
50%     96.779938   97.000000   97.490799   97.824120   98.385853   98.701241   
75%    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
max    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   

             2015        2016  2017  Unnamed: 62  
count  261.000000  261.000000   0.0          0.0  
mean    82.750795   83.550868   NaN          NaN  
std     26.898025   25.961317   NaN          NaN  
min      7.252090    7.588477   NaN          NaN  
25%     71.500000   75.920000   NaN          NaN  
50%     99.032677   99.427812   NaN          NaN  
75%    100.000000  100.000000   NaN          NaN  
max    100.000000  100.000000   NaN          NaN  

[8 rows x 28 columns]

In [8]:
winter_raw.head(5)

Year      City     Sport Discipline               Athlete Country Gender  \
0  1924  Chamonix  Biathlon   Biathlon           BERTHET, G.     FRA    Men   
1  1924  Chamonix  Biathlon   Biathlon        MANDRILLON, C.     FRA    Men   
2  1924  Chamonix  Biathlon   Biathlon   MANDRILLON, Maurice     FRA    Men   
3  1924  Chamonix  Biathlon   Biathlon       VANDELLE, André     FRA    Men   
4  1924  Chamonix  Biathlon   Biathlon  AUFDENBLATTEN, Adolf     SUI    Men   

             Event   Medal  
0  Military Patrol  Bronze  
1  Military Patrol  Bronze  
2  Military Patrol  Bronze  
3  Military Patrol  Bronze  
4  Military Patrol    Gold

In [9]:
medals = dict() # by countries code => by years


for i in range(len(winter_raw)):
    row = dict(winter_raw.iloc[i, :])
    ccode = row["Country"]
    year  = row["Year"]
    medal = row["Medal"]
    if int(year) < DROP_TO:
        continue
        
    YEARS.add(year)
    medals.setdefault(ccode, dict()).setdefault(year, 0)
    medals[ccode][year] += 1
print("total country medalists", len(medals))

total country medalists 37


In [10]:
winter = pd.DataFrame(table["population"]["Country"])
for i, year in enumerate(YEARS):
    winter[year] = np.zeros(len(winter))
    for ccode, _ in medals.items():
        medals[ccode].setdefault(year, 0)
        winter.loc[winter.Country==ccode, year] = medals[ccode][year]

In [11]:
winter.head(5)

Country  1992  1994  1998  2002  2006  2010  2014
0     ABW   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1     AFG   0.0   0.0   0.0   0.0   0.0   0.0   0.0
2     AGO   0.0   0.0   0.0   0.0   0.0   0.0   0.0
3     ALB   0.0   0.0   0.0   0.0   0.0   0.0   0.0
4     AND   0.0   0.0   0.0   0.0   0.0   0.0   0.0

In [12]:
winter.loc[winter.Country=="RUS"]

Country  1992  1994  1998  2002  2006  2010  2014
200     RUS   0.0  36.0  53.0  40.0  41.0  25.0  68.0

In [13]:
for year in YEARS:
    for key, _ in table.items():
        table[key][str(year)].fillna(table[key][str(year)].mean())
    winter[year].fillna(winter[year].mean())

In [15]:
winter.head(5)

Country  1992  1994  1998  2002  2006  2010  2014
0     ABW   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1     AFG   0.0   0.0   0.0   0.0   0.0   0.0   0.0
2     AGO   0.0   0.0   0.0   0.0   0.0   0.0   0.0
3     ALB   0.0   0.0   0.0   0.0   0.0   0.0   0.0
4     AND   0.0   0.0   0.0   0.0   0.0   0.0   0.0

In [25]:
winter.loc[winter.Country=="RUS", 1994]

200    36.0
Name: 1994, dtype: float64

In [29]:
X  = [] # population, pcgdp normed in year = year
y  = [] # medals
y2 = [] # classification, if have medals
for year in YEARS:
        features = np.array([table["population"].loc[table["population"].Country==country, str(year)], 
                    table["pcgdp"].loc[table["pcgdp"].Country==country, str(year)]])
        target = int(winter.loc[winter.Country==country][year])
        X.append(features)
        y.append(target)
        y2.append(target > 0)
    

ABW
[[68235.]
 [   nan]]
AFG
[[13981231.]
 [      nan]]
AGO
[[1.2968345e+07]
 [4.3832052e+02]]
ALB
[[3.24703900e+06]
 [2.18492166e+02]]
AND
[[58888.        ]
 [20547.71178979]]
ARB
[[2.35037179e+08]
 [2.00463398e+03]]
ARE
[[2086639.        ]
 [  25993.55800777]]
ARG
[[3.36551510e+07]
 [6.79802676e+03]]
ARM
[[3.44281000e+06]
 [3.69633368e+02]]
ASM
[[49593.]
 [   nan]]
ATG
[[68427.        ]
 [ 7296.55177266]]
AUS
[[17495000.        ]
 [   18616.32080552]]
AUT
[[7840709.        ]
 [  24880.16407012]]
AZE
[[7.38200000e+06]
 [6.76151511e+02]]
BDI
[[5.66113900e+06]
 [1.91310913e+02]]
BEL
[[10045158.        ]
 [   23497.72740674]]
BEN
[[5.33180300e+06]
 [3.17962855e+02]]
BFA
[[9.29711300e+06]
 [2.40963481e+02]]
BGD
[[1.11221938e+08]
 [2.85095499e+02]]
BGR
[[8.54016400e+06]
 [1.21198088e+03]]
BHR
[[523087.        ]
 [  9082.74116884]]
BHS
[[266134.        ]
 [ 11682.08496472]]
BIH
[[4239154.]
 [     nan]]
BLR
[[1.02160000e+07]
 [1.67583892e+03]]
BLZ
[[194317.        ]
 [  2666.97767051]]
BMU
[

 [ 6128.44556922]]
SYR
[[1.31870850e+07]
 [1.00504136e+03]]
TCA
[[12968.]
 [   nan]]
TCD
[[6.34908900e+06]
 [2.96396487e+02]]
TEA
[[1.63096331e+09]
 [4.98434649e+02]]
TEC
[[4.31844672e+08]
 [2.18669526e+03]]
TGO
[[3.97332700e+06]
 [4.26080992e+02]]
THA
[[5.78378780e+07]
 [1.92698752e+03]]
TJK
[[5.50297600e+06]
 [3.46948022e+02]]
TKM
[[3.89984300e+06]
 [8.20684273e+02]]
TLA
[[4.46211495e+08]
 [2.89247298e+03]]
TLS
[[805435.]
 [    nan]]
TMN
[[2.3689906e+08]
 [          nan]]
TON
[[95496.        ]
 [ 1435.30923337]]
TSA
[[1.18325353e+09]
 [3.21004753e+02]]
TSS
[[5.41365685e+08]
 [5.81503840e+02]]
TTO
[[1237487.        ]
 [   4395.64451277]]
TUN
[[8.60322500e+06]
 [1.80133453e+03]]
TUR
[[5.5748875e+07]
 [2.8423736e+03]]
TUV
[[9109.       ]
 [1069.5959459]]
TZA
[[2.72196190e+07]
 [1.73891383e+02]]
UGA
[[1.86528890e+07]
 [1.53191168e+02]]
UKR
[[5.2150266e+07]
 [1.4178688e+03]]
UMC
[[2.09490102e+09]
 [1.37060293e+03]]
URY
[[3154855.        ]
 [   4082.01242395]]
USA
[[2.56514000e+08]
 [2.549

[[3419048.        ]
 [  21578.46053253]]
SLB
[[349225.        ]
 [  1330.82293224]]
SLE
[[4.28362100e+06]
 [2.12884373e+02]]
SLV
[[5.544945e+06]
 [1.458193e+03]]
SMR
[[25516.]
 [   nan]]
SOM
[[7583954.]
 [     nan]]
SRB
[[7734639.]
 [     nan]]
SSA
[[5.71754398e+08]
 [5.11700042e+02]]
SSD
[[5431738.]
 [     nan]]
SSF
[[5.71828603e+08]
 [5.12490442e+02]]
SST
[[2.68810010e+07]
 [3.10530142e+03]]
STP
[[123973.]
 [    nan]]
SUR
[[437037.        ]
 [  1385.44914347]]
SVK
[[5.34633100e+06]
 [3.75572774e+03]]
SVN
[[1989443.]
 [     nan]]
SWE
[[8780745.        ]
 [  25747.24168755]]
SWZ
[[941774.        ]
 [  1507.04251232]]
SXM
[[nan]
 [nan]]
SYC
[[74205.        ]
 [ 6555.50440748]]
SYR
[[1.39496970e+07]
 [7.25608592e+02]]
TCA
[[14597.]
 [   nan]]
TCD
[[6.77213300e+06]
 [1.74219549e+02]]
TEA
[[1.67431879e+09]
 [6.41488899e+02]]
TEC
[[4.34111200e+08]
 [1.92863844e+03]]
TGO
[[4.16364200e+06]
 [2.36001156e+02]]
THA
[[5.89016660e+07]
 [2.49031155e+03]]
TJK
[[5.67983200e+06]
 [2.36991976e+02]]
TKM

 [1.86499139e+03]]
RUS
[[1.47670692e+08]
 [1.83484694e+03]]
RWA
[[7.05981300e+06]
 [2.81784163e+02]]
SAS
[[1.33577764e+09]
 [4.12964149e+02]]
SAU
[[1.9882458e+07]
 [7.3821606e+03]]
SDN
[[2.6003542e+07]
 [3.5043968e+02]]
SEN
[[9.41839300e+06]
 [5.34097916e+02]]
SGP
[[3927213.        ]
 [  21824.03557772]]
SLB
[[390643.        ]
 [  1206.15756089]]
SLE
[[4.35364600e+06]
 [1.54439733e+02]]
SLV
[[5.77870600e+06]
 [2.07804308e+03]]
SMR
[[26799.]
 [   nan]]
SOM
[[8422372.]
 [     nan]]
SRB
[[7.56774500e+06]
 [2.41606908e+03]]
SSA
[[6.36103731e+08]
 [5.36029462e+02]]
SSD
[[6099923.]
 [     nan]]
SSF
[[6.36182577e+08]
 [5.36926743e+02]]
SST
[[2.85281590e+07]
 [3.74241766e+03]]
STP
[[133418.]
 [    nan]]
SUR
[[461560.        ]
 [  2047.40445446]]
SVK
[[5390516.        ]
 [   5533.58884488]]
SVN
[[1981629.        ]
 [  11165.27633184]]
SWE
[[8850974.        ]
 [  30143.62745828]]
SWZ
[[1026009.        ]
 [   1536.93027299]]
SXM
[[31240.]
 [   nan]]
SYC
[[78846.        ]
 [ 7715.91814709]]
SYR
[[

[[23336681.]
 [      nan]]
PRT
[[10419631.        ]
 [   12882.28897303]]
PRY
[[5.50861100e+06]
 [1.14822988e+03]]
PSE
[[3.07537300e+06]
 [1.15621747e+03]]
PSS
[[2.00644100e+06]
 [1.76692475e+03]]
PST
[[1.03074233e+09]
 [2.63604791e+04]]
PYF
[[245006.]
 [    nan]]
QAT
[[645659.        ]
 [ 29990.65491805]]
ROU
[[2.17304960e+07]
 [2.12487361e+03]]
RUS
[[1.45306046e+08]
 [2.37505904e+03]]
RWA
[[8.53620500e+06]
 [1.96509708e+02]]
SAS
[[1.43756823e+09]
 [4.61369523e+02]]
SAU
[[2.19063080e+07]
 [8.65531153e+03]]
SDN
[[2.86795650e+07]
 [4.12151756e+02]]
SEN
[[1.03968610e+07]
 [5.13026227e+02]]
SGP
[[4175950.        ]
 [  22016.83279164]]
SLB
[[435262.        ]
 [   784.95628737]]
SLE
[[4.9572160e+06]
 [2.4993954e+02]]
SLV
[[5.9403030e+06]
 [2.4084125e+03]]
SMR
[[28121.        ]
 [44576.26256591]]
SOM
[[9564167.]
 [     nan]]
SRB
[[7.4965220e+06]
 [2.1499094e+03]]
SSA
[[7.07016127e+08]
 [5.19585844e+02]]
SSD
[[7237276.]
 [     nan]]
SSF
[[7.07099850e+08]
 [5.20518915e+02]]
SST
[[3.03522980e+0

[[1.96566200e+06]
 [9.15775749e+02]]
LTE
[[2.12983887e+09]
 [3.49170798e+03]]
LTU
[[3269909.        ]
 [   9240.64254797]]
LUX
[[472637.        ]
 [ 89739.71169613]]
LVA
[[2218357.        ]
 [   9667.97570008]]
MAC
[[493320.        ]
 [ 29979.85447414]]
MAF
[[28414.]
 [   nan]]
MAR
[[3.08693460e+07]
 [2.19147857e+03]]
MCO
[[ 34408.        ]
 [135535.00241507]]
MDA
[[3.58520900e+06]
 [9.50648204e+02]]
MDG
[[1.88802680e+07]
 [2.92150744e+02]]
MDV
[[327371.        ]
 [  4811.66746882]]
MEA
[[3.56287693e+08]
 [5.02666655e+03]]
MEX
[[1.10092378e+08]
 [8.76792026e+03]]
MHL
[[52078.        ]
 [ 2763.73900687]]
MIC
[[4.98389967e+09]
 [2.31156788e+03]]
MKD
[[2063145.       ]
 [   3325.6132419]]
MLI
[[1.3227064e+07]
 [5.2164258e+02]]
MLT
[[405308.        ]
 [ 16671.56719926]]
MMR
[[4.88464740e+07]
 [2.96900728e+02]]
MNA
[[3.12079307e+08]
 [2.59990141e+03]]
MNE
[[615025.        ]
 [  4383.59509708]]
MNG
[[2.5580120e+06]
 [1.3346519e+03]]
MNP
[[61688.       ]
 [16048.5021398]]
MOZ
[[2.15474630e+07

[[1.46304170e+07]
 [2.82552407e+03]]
GUM
[[159444.        ]
 [ 30700.43400818]]
GUY
[[746556.        ]
 [  3044.94912902]]
HIC
[[1.14951378e+09]
 [3.93269527e+04]]
HKG
[[7024200.        ]
 [  32549.99823112]]
HND
[[8.19477800e+06]
 [1.93285829e+03]]
HPC
[[6.30127436e+08]
 [7.42471894e+02]]
HRV
[[4417781.        ]
 [  13505.74586303]]
HTI
[[9.99961700e+06]
 [6.62279518e+02]]
HUN
[[10000023.        ]
 [   13092.23375677]]
IBD
[[4.43002264e+09]
 [4.50876827e+03]]
IBT
[[5.80357073e+09]
 [3.69178506e+03]]
IDA
[[1.37354809e+09]
 [1.05937221e+03]]
IDB
[[4.52947421e+08]
 [1.56140389e+03]]
IDN
[[2.42524123e+08]
 [3.11348063e+03]]
IDX
[[9.20600670e+08]
 [8.06079684e+02]]
IMN
[[80072.        ]
 [73935.67899521]]
IND
[[1.23098069e+09]
 [1.34577015e+03]]
INX
[[nan]
 [nan]]
IRL
[[4560155.        ]
 [  48671.88829361]]
IRN
[[7.45675110e+07]
 [6.53192743e+03]]
IRQ
[[3.07627010e+07]
 [4.50274905e+03]]
ISL
[[318041.       ]
 [ 41851.7354773]]
ISR
[[7623600.        ]
 [  30642.94061749]]
ITA
[[5.92774170

[[8.09825000e+07]
 [4.80425634e+04]]
DJI
[[912164.       ]
 [  1740.9150109]]
DMA
[[72778.        ]
 [ 7195.39348989]]
DNK
[[5643475.        ]
 [  62548.98501744]]
DOM
[[1.04058440e+07]
 [6.26869212e+03]]
DZA
[[3.91133130e+07]
 [5.46642578e+03]]
EAP
[[2.02383710e+09]
 [6.30191913e+03]]
EAR
[[3.08423644e+09]
 [3.41409299e+03]]
EAS
[[2.26774532e+09]
 [9.65792611e+03]]
ECA
[[4.12510951e+08]
 [9.88784805e+03]]
ECS
[[9.03094670e+08]
 [2.61929481e+04]]
ECU
[[1.59031120e+07]
 [6.39663048e+03]]
EGY
[[9.18125660e+07]
 [3.32775425e+03]]
EMU
[[3.38429648e+08]
 [3.98202511e+04]]
ERI
[[nan]
 [nan]]
ESP
[[4.64808820e+07]
 [2.96231644e+04]]
EST
[[1314545.       ]
 [  19949.5813767]]
ETH
[[9.73667740e+07]
 [5.71162276e+02]]
EUU
[[5.08157248e+08]
 [3.66664275e+04]]
FCS
[[4.82474449e+08]
 [1.77210299e+03]]
FIN
[[5461512.        ]
 [  49914.61864216]]
FJI
[[885806.        ]
 [  5045.76992638]]
FRA
[[6.63319585e+07]
 [4.29552419e+04]]
FRO
[[48842.        ]
 [57543.66905915]]
FSM
[[104015.        ]
 [  305

In [30]:
X

[array([[68235.],
        [   nan]]), array([[13981231.],
        [      nan]]), array([[1.2968345e+07],
        [4.3832052e+02]]), array([[3.24703900e+06],
        [2.18492166e+02]]), array([[58888.        ],
        [20547.71178979]]), array([[2.35037179e+08],
        [2.00463398e+03]]), array([[2086639.        ],
        [  25993.55800777]]), array([[3.36551510e+07],
        [6.79802676e+03]]), array([[3.44281000e+06],
        [3.69633368e+02]]), array([[49593.],
        [   nan]]), array([[68427.        ],
        [ 7296.55177266]]), array([[17495000.        ],
        [   18616.32080552]]), array([[7840709.        ],
        [  24880.16407012]]), array([[7.38200000e+06],
        [6.76151511e+02]]), array([[5.66113900e+06],
        [1.91310913e+02]]), array([[10045158.        ],
        [   23497.72740674]]), array([[5.33180300e+06],
        [3.17962855e+02]]), array([[9.29711300e+06],
        [2.40963481e+02]]), array([[1.11221938e+08],
        [2.85095499e+02]]), array([[8.540164